kind: Service
apiVersion: v1
metadata:
  name: ayu-dag-frontend-service
spec:
  selector:
    app: ayu-dag-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ayu-dag-frontend
  labels:
    app: ayu-dag-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayu-dag-frontend
  template:
    metadata:
      labels:
        app: ayu-dag-frontend
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
              hostPort: 4200
              name: 80tcp4200
              protocol: TCP
