kind: Service
apiVersion: v1
metadata:
  name: ayu_dag_frontend-service
spec:
  selector:
    app: ayu_dag_frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ayu_dag_frontend
  labels:
    app: ayu_dag_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayu_dag_frontend
  template:
    metadata:
      labels:
        app: ayu_dag_frontend
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: maven
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080
