version: '3.7'

services:
  front:
    image: nemchinovrp/angulardockertest:1.0.0
    restart: on-failure
    ports:
      - 80:80
#  back:
#    image: xpendence/db-back:1.0.8
#    restart: on-failure
#    ports:
#      - 8099:8099
